source:
  type: cardano_net
  relay:
    - cardano-node
    - 3001
      # - relays-new.cardano-mainnet.iohk.io
      # - 3001
      # - preview-node.world.dev.cardano.org
      # - 30002
      # - preprod-node.world.dev.cardano.org
      # - 30000

sink:
  type: cardano
  db:
    type: postgres
    host: postgres # name of postgres container
    port: 5432 # internal postgres port
    user: carp
    password: ""
    db: carp_mainnet
  network: mainnet # preview / preprod / testnet

start_block:
