source:
#  type: oura
#  network: mainnet
#  socket: "relays-new.cardano-mainnet.iohk.io:3001"
#  bearer: tcp
  type: cardano_net
  relay: 
    - relays-new.cardano-mainnet.iohk.io
    - 3001
      # - preview-node.world.dev.cardano.org
      # - 30002
      # - preprod-node.world.dev.cardano.org
      # - 30000

sink:
  type: cardano
  db:
    type: postgres
    host: localhost
    port: 5432
    user: carp
    password: "1234"
    db: carp_mainnet
  network: mainnet

start_block:
