source:
  type: oura
  socket: "relays-new.cardano-mainnet.iohk.io:3001"
  bearer: Tcp # Unix

sink:
  type: cardano
  db:
    type: postgres
    host: localhost
    port: 5432
    user: carp
    password: "1234"
    db: carp_mainnet
  network: mainnet # preview / preprod / testnet

start_block:
